export default {
  data: [
    {
      id: "22",
      type: "educational_qualification",
      attributes: {
        id: 22,
        school_name: "school_name",
        start_date: "2022-12-06",
        end_date: "2022-12-07",
        grades: "A",
        description: "testing",
        make_grades_public: false,
        degree_name: null,
        field_of_study: null,
        profile_id: 1,
      },
    },
    {
      id: "24",
      type: "educational_qualification",
      attributes: {
        id: 24,
        school_name: "school_name",
        start_date: "2022-12-06",
        end_date: "2022-12-07",
        grades: "A",
        description: "testing",
        make_grades_public: false,
        degree_name: null,
        field_of_study: null,
        profile_id: 1,
      },
    },
    {
      id: "25",
      type: "educational_qualification",
      attributes: {
        id: 25,
        school_name: "school_name",
        start_date: "2022-12-06",
        end_date: "2022-12-07",
        grades: "A",
        description: "testing",
        make_grades_public: false,
        degree_name: "B.E",
        field_of_study: null,
        profile_id: 1,
      },
    },
    {
      id: "26",
      type: "educational_qualification",
      attributes: {
        id: 26,
        school_name: "school_name",
        start_date: "2022-12-06",
        end_date: "2022-12-07",
        grades: "A",
        description: "testing",
        make_grades_public: false,
        degree_name: "B.E",
        field_of_study: "Testing Again field_of_study",
        profile_id: 1,
      },
    },
    {
      id: "23",
      type: "educational_qualification",
      attributes: {
        id: 23,
        school_name: "Testing",
        start_date: "2022-01-01",
        end_date: "2022-02-02",
        grades: "sed anim ad",
        description: "ea reprehenderit",
        make_grades_public: false,
        degree_name: "B.E",
        field_of_study: "I.T",
        profile_id: 1,
      },
    },
    {
      id: "27",
      type: "educational_qualification",
      attributes: {
        id: 27,
        school_name: "Testing",
        start_date: "2022-01-01",
        end_date: "2022-02-02",
        grades: "sed anim ad",
        description: "ea reprehenderit",
        make_grades_public: false,
        degree_name: "B.E",
        field_of_study: "I.T",
        profile_id: 1,
      },
    },
  ],
  meta: { message: "Successfully Loaded" },
};
